apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-template
spec:
  replicas: 2
  selector:
    matchLabels:
      app: site-template
  template:
    metadata:
      labels:
        app: site-template
    spec:
      containers:
        - name: site-template
          image: elioenaiferrari/site-template
          ports:
            - containerPort: 3333
