version: '3'

services:
  nginx:
    image: nginx
    container_name: $APP_NAME-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./ssl/certificate.crt:/etc/ssl/certificate.crt
      - ./ssl/certificate.key:/etc/ssl/certificate.key
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    networks:
      - app_network
  # db:
  #   image: mongo
  #   command: mongod
  #   container_name: $APP_NAME-db
  #   restart: always
  #   volumes:
  #     - ./database/configdb:/data/configdb
  #     - ./database/db:/data/db
  #   networks:
  #     - app_network
  #   environment:
  #     - MONGO_INITDB_DATABASE=$DB_NAME
  #     - MONGO_INITDB_ROOT_USERNAME=$DB_USER
  #     - MONGO_INITDB_ROOT_PASSWORD=$DB_PASS

  app:
    build: .
    container_name: $APP_NAME-app
    image: elioenaiferrari/$APP_NAME
    restart: always
    # depends_on:
    #   - db
    # links:
    #   - db
    ports:
      - $APP_PORT:$APP_PORT
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
    environment:
      - APP_NAME=$APP_NAME
      - APP_HOST=$APP_HOST
      - APP_PORT=$APP_PORT
      - APP_SECRET=$APP_SECRET
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
